name: CI/CD for Flat File Site

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown pandoc  # Ajoutez vos autres dépendances Python ici

    - name: Set up Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Run Python scripts to generate HTML
      run: |
        python scripts/gen_index.py
        python scripts/gen_bureau.py

    - name: List generated files
      run: ls -R ./scripts

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./scripts
