name: CI/CD for Flat File Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown pandoc pytest

    - name: Set up tools
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc tidy curl

    - name: Make gen_all.sh executable
      run: chmod +x scripts/gen_all.sh

    - name: Run all scripts
      run: bash scripts/gen_all.sh

    - name: Validate HTML
      run: |
        cd ./site
        tidy -e *.html || exit 1

    - name: List generated files
      run: ls -R ./site

    - name: Run unit and integration tests
      run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site

    - name: Smoke test with curl
      run: |
        sleep 30
        curl -s -o /dev/null -w "%{http_code}" https://<USERNAME>.github.io/<REPO_NAME> | grep 200
